<?xml version="1.0"?>
<robot name="arm_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants -->
  <xacro:property name="density" value="2710"/> <!-- Aluminum density kg/mÂ³ -->
  <xacro:property name="pi" value="3.1415926535897931"/>

  <!-- Materials -->
  <material name="aluminum">
    <color rgba="0.7 0.7 0.7 1"/>
  </material>
  <material name="gripper_color">
    <color rgba="0.9 0.9 0.9 1"/>
  </material>

  <!-- Generic Cylinder Macro -->
  <xacro:macro name="cylinder_link" params="name radius length origin_xyz origin_rpy">
    <link name="${name}">
      <xacro:property name="mass" value="${density * pi * radius*radius * length}"/>
      
      <visual>
        <origin rpy="${origin_rpy}" xyz="${origin_xyz}"/>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <material name="aluminum"/>
      </visual>

      <collision>
        <origin rpy="${origin_rpy}" xyz="${origin_xyz}"/>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
      </collision>

      <inertial>
        <origin rpy="${origin_rpy}" xyz="${origin_xyz}"/>
        <mass value="${mass}"/>
        <inertia
          ixx="${(mass/12) * (3*radius*radius + length*length)}"
          ixy="0"
          ixz="0"
          iyy="${(mass/12) * (3*radius*radius + length*length)}"
          iyz="0"
          izz="${0.5 * mass * radius*radius}"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- Generic Box Macro -->
  <xacro:macro name="box_link" params="name size_x size_y size_z origin_xyz origin_rpy">
    <link name="${name}">
      <xacro:property name="mass" value="${density * size_x * size_y * size_z}"/>
      
      <visual>
        <origin rpy="${origin_rpy}" xyz="${origin_xyz}"/>
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
        <material name="aluminum"/>
      </visual>

      <collision>
        <origin rpy="${origin_rpy}" xyz="${origin_xyz}"/>
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}"/>
        </geometry>
      </collision>

      <inertial>
        <origin rpy="${origin_rpy}" xxyz="${origin_xyz}"/>
        <mass value="${mass}"/>
        <inertia
          ixx="${(mass/12) * (size_y*size_y + size_z*size_z)}"
          ixy="0"
          ixz="0"
          iyy="${(mass/12) * (size_x*size_x + size_z*size_z)}"
          iyz="0"
          izz="${(mass/12) * (size_x*size_x + size_y*size_y)}"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- Arm Link Components -->
  <xacro:box_link name="base_link" 
    size_x="0.2" size_y="1" size_z="0.1"
    origin_xyz="0 0 0" origin_rpy="0 0 0"/>

  <xacro:cylinder_link name="arm1_p_link" 
    radius="0.1" length="0.1"
    origin_xyz="0 0 0" origin_rpy="0 0 0"/>
  
  <xacro:cylinder_link name="arm1_r_link" 
    radius="0.1" length="0.1"
    origin_xyz="0 0 0" origin_rpy="0 0 0"/>

  <xacro:cylinder_link name="arm2_link" 
    radius="0.1" length="0.5"
    origin_xyz="0 0 ${(0.5-0.1)/2}" origin_rpy="0 0 0"/>

  <xacro:cylinder_link name="arm3_link" 
    radius="0.1" length="0.5"
    origin_xyz="0 0 ${(0.5-0.1)/2}" origin_rpy="0 0 0"/>

  <xacro:cylinder_link name="arm4_link" 
    radius="0.08" length="0.5"
    origin_xyz="0 0 ${(0.5-0.1)/2}" origin_rpy="0 0 0"/>

  <xacro:cylinder_link name="arm5_link"
    radius="0.1" length="0.02"
    origin_xyz="0 0 0" origin_rpy="0 0 0"/>

  <xacro:box_link name="arm6_link"
    size_x="0.02" size_y="0.2" size_z="0.02"
    origin_xyz="0 0 0" origin_rpy="0 0 0"/>

  <!-- Arm Joints -->

  <joint name="arm1_p_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="arm1_p_link"/>
    <origin rpy="0 0 0" xyz="0 0 0.1"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.4" upper="0.4" effort="100" velocity="0.1"/>
  </joint>

  <joint name="arm1_r_joint" type="revolute">
    <parent link="arm1_p_link"/>
    <child link="arm1_r_link"/>
    <origin rpy="0 0 0" xyz="0 0 0.1"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1.57" upper="1.57" effort="100" velocity="0.1"/>
  </joint>

  <joint name="arm2_joint" type="revolute">
    <parent link="arm1_r_link"/>
    <child link="arm2_link"/>
    <origin rpy="0 0 0" xyz="0 -0.2 -0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.68" upper="2.01" effort="100" velocity="0.1"/>
  </joint>

  <joint name="arm3_joint" type="revolute">
    <parent link="arm2_link"/>
    <child link="arm3_link"/>
    <origin rpy="0 0 0" xyz="0 0.2 0.4"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.80" upper="2.80" effort="100" velocity="0.1"/>
  </joint>

  <joint name="arm4_joint" type="prismatic">
    <parent link="arm3_link"/>
    <child link="arm4_link"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="0.5" effort="100" velocity="0.1"/>
  </joint>

  <joint name="arm5_joint" type="revolute">
    <parent link="arm4_link"/>
    <child link="arm5_link"/>
    <origin rpy="0 0 0" xyz="0 0 0.45"/>
    <axis xyz="0 0 1"/>
    <limit lower="-2.80" upper="2.80" effort="100" velocity="0.1"/>
  </joint>

  <joint name="arm6_joint" type="fixed">
    <parent link="arm5_link"/>
    <child link="arm6_link"/>
    <origin rpy="0 0 0" xyz="0 0 0.02"/>
  </joint>

  <!-- Gripper Components -->

  <xacro:box_link name="gripper_left"
    size_x="0.02" size_y="0.02" size_z="0.1"
    origin_xyz="0 0 0" origin_rpy="0 0 0"/>

  <xacro:box_link name="gripper_right"
    size_x="0.02" size_y="0.02" size_z="0.1"
    origin_xyz="0 0 0" origin_rpy="0 0 0"/>

  <joint name="gripper_joint1" type="prismatic">
    <parent link="arm6_link"/>
    <child link="gripper_left"/>
    <origin rpy="0 0 0" xyz="0 0.09 0.05"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.08" upper="0" effort="100" velocity="0.1"/>
  </joint>

  <joint name="gripper_joint2" type="prismatic">
    <parent link="arm6_link"/>
    <child link="gripper_right"/>
    <origin rpy="0 0 0" xyz="0 -0.09 0.05"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="0.08" effort="100" velocity="0.1"/>
  </joint>

  <!-- Transmission Import -->
  <xacro:include filename="$(find irwb_robot_pkg)/urdf/transmissions.xacro"/>

</robot>