irwb_full:
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm1_p_joint
      - arm1_r_joint
      - arm2_joint
      - arm3_joint
      - arm4_joint
      - arm5_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.01
      arm1_p_joint: {trajectory: 0.1, goal: 0.1}
      arm1_r_joint: {trajectory: 0.1, goal: 0.1}
      arm2_joint: {trajectory: 0.1, goal: 0.1}
      arm3_joint: {trajectory: 0.1, goal: 0.1}
      arm4_joint: {trajectory: 0.1, goal: 0.1}
      arm5_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - gripper_joint1
      - gripper_joint2
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.01
      gripper_joint1: {trajectory: 0.1, goal: 0.1}
      gripper_joint2: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10